[window]
opacity = 1
blur = false
padding = { x = 5, y = 5 }

[window.class]
instance = "Alacritty"
general = "Alacritty"

[font]
normal = { family = "Hack", style = "Regular" }
bold = { family = "Hack", style = "Bold" }
italic = { family = "Hack", style = "Italic" }
bold_italic = { family = "Hack", style = "BoldItalic" }
size = 10

[terminal]
shell = "/usr/bin/fish"

[cursor]
style = { shape = "Underline", blinking = "Always" }
blink_timeout = 0

[mouse]
hide_when_typing = true

[colors.primary]
background = "#101115"
foreground = "#c3c3c4"

[colors.cursor]
text = "#101115"
cursor = "#c3c3c4"

[colors.vi_mode_cursor]
text = "#101115"
cursor = "#c3c3c4"

[colors.search.matches]
foreground = "#101115"
background = "#c3c3c4"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#5a616e"
background = "#c3c3c4"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#101115"
red = "#3C53B0"
green = "#5264A3"
yellow = "#4268C3"
blue = "#7389A9"
magenta = "#B1AB9E"
cyan = "#E8CD9D"
white = "#c3c3c4"

[colors.bright]
black = "#5a616e"
red = "#3C53B0"
green = "#5264A3"
yellow = "#4268C3"
blue = "#7389A9"
magenta = "#B1AB9E"
cyan = "#E8CD9D"
white = "#c3c3c4"

[colors.dim]
black = "#c3c3c4"
red = "#3C53B0"
green = "#B1AB9E"
yellow = "#4268C3"
blue = "#7389A9"
magenta = "#5264A3"
cyan = "#E8CD9D"
white = "#5a616e"


