# Apps

exec-once = discord
exec-once = firefox

# Core

exec-once = waybar
exec-once = swww-daemon --format xrgb
exec = hyprshade on vibrance
exec-once = fcitx5
exec-once = hypridle
exec-once = swaync

# Cursor
exec-once = hyprctl setcursor Future-Cyan-Hyprcursor 35