### MY PROGRAMS ###

$terminal = alacritty
$fileManager = nautilus
$menu = rofi -display-drun " " -modi drun -show drun -font "Hack 20" -show-icons -yoffset -310

### KEYBINDINGS ###

bind = Super, Q, exec, $terminal
bind = Super, C, killactive,
bind = Super, M, exit,
bind = Super, E, exec, $fileManager
bind = Super + Alt, Space, togglefloating,
bind = Super, Space, exec, $menu
bind = Super, P, pseudo, # dwindle
bind = Super, J, togglesplit, # dwindle
bind = Super+Shift, C, exec, hyprpicker -a
bind = Super+Shift+Alt, C, exec, hyprctl kill
bindr = CTRL + SUPER, R, exec, bash -c 'hyprctl reload && pkill waybar && sleep 1 && waybar &'
bind = Shift + Super, S, exec, bash -c 'mkdir -p ~/Pictures/screenshots && FILE=~/Pictures/screenshots/screenshot_$(date +%s).png && grim -g "$(slurp)" - | tee "$FILE" | wl-copy --type image/png'
bind = , Print, exec, bash -c 'mkdir -p ~/Pictures/screenshots && FILE=~/Pictures/screenshots/screenshot_$(date +%s).png && grim "$FILE" && wl-copy < "$FILE"'
bind = Super, N, exec, swaync-client -t -sw
bind = Ctrl + Alt, Delete, exec, wlogout
bind = Super, L, exec, hyprlock

# Move focus with mainMod + arrow keys
bind = Super, left, movefocus, l
bind = Super, right, movefocus, r
bind = Super, up, movefocus, u
bind = Super, down, movefocus, d

# Switch workspaces with mainMod + [0-9]
bind = Super, 1, workspace, 1
bind = Super, 2, workspace, 2
bind = Super, 3, workspace, 3
bind = Super, 4, workspace, 4
bind = Super, 5, workspace, 5
bind = Super, 6, workspace, 6
bind = Super, 7, workspace, 7
bind = Super, 8, workspace, 8
bind = Super, 9, workspace, 9
bind = Super, 0, workspace, 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = Super Alt, 1, movetoworkspacesilent, 1
bind = Super Alt, 2, movetoworkspacesilent, 2
bind = Super Alt, 3, movetoworkspacesilent, 3
bind = Super Alt, 4, movetoworkspacesilent, 4
bind = Super Alt, 5, movetoworkspacesilent, 5
bind = Super Alt, 6, movetoworkspacesilent, 6
bind = Super Alt, 7, movetoworkspacesilent, 7
bind = Super Alt, 8, movetoworkspacesilent, 8
bind = Super Alt, 9, movetoworkspacesilent, 9
bind = Super Alt, 0, movetoworkspacesilent, 10

# Example special workspace (scratchpad)
bind = Super, S, togglespecialworkspace, magic
bind = Super Alt, S, movetoworkspacesilent, special:magic

# Scroll through existing workspaces with mainMod + scroll
bind = Super, mouse_down, workspace, e+1
bind = Super, mouse_up, workspace, e-1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = Super, mouse:272, movewindow
bindm = Super, mouse:273, resizewindow

# Laptop multimedia keys for volume and LCD brightness
bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindel = ,XF86MonBrightnessUp, exec, brightnessctl -e4 -n2 set 5%+
bindel = ,XF86MonBrightnessDown, exec, brightnessctl -e4 -n2 set 5%-

# Requires playerctl
bindl = , XF86AudioNext, exec, playerctl next
bindl = , XF86AudioPause, exec, playerctl play-pause
bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF86AudioPrev, exec, playerctl previous

bind = Super, F, fullscreen, 0
bind = Super, D, fullscreen, 1

### AUDIO ###

# Volume control using wpctl
bind = SUPER, UP, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bind = SUPER, DOWN, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bind = SUPER, H, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

### WALLPAPER ###
bind = CTRL+SUPER, T, exec, sh -c '~/.config/hypr/scripts/wal.sh'
